#   xdot make file
#   Written by Emden R. Gansner (6 August 2007)
ALL = libxdot.a
all : $(ALL)

include ../../Config.mk
include ../../makearch/$(ARCH)

INCS = -I.

OBJS = xdot.o

libxdot.a : $(OBJS)
	$(RM) libxdot.a
	$(AR) cr libxdot.a $(OBJS)
	$(RANLIB) libxdot.a

install : all
	$(MKPATH) $(LIBDIR)
	$(CP) prune $(LIBDIR)
	$(MKPATH) $(MANDIR)
	$(INSTALL) prune.1 $(MANDIR)

clean :
	$(RM) core *.o 

distclean : clean
	$(RM) $(ALL)
